Parameters:
  NameOfTheService:
    Description: The name of the service this tag to be used for.
    Type: String 
  KeyName: 
    Description: Name of the existen keypair to enable ssh access to the server
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0453ec754f44f9a4a
    us-west-1:
      AMI: ami-bf5540df
    ap-southeast-1:
      AMI: ami-3bfab942
    ap-southeast-2:
      AMI: ami-43874721
      
Resources:
  MyEc2Instance:
    Type : 'AWS::EC2::Instance'
    Properties: 
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI 
      InstanceType: 't2.micro'
      Tags:
        - Key: "name"
          Value: !Ref NameOfTheService
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: !Ref KeyName

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access via port 22'
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0